after-startup-command = [
  'exec-and-forget /usr/local/bin/sketchybar --reload',
  'exec-and-forget /usr/local/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  '/usr/local/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget /usr/local/bin/borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'camera'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'preview'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'mail'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-name-regex-substring = 'whatsapp'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-name-regex-substring = 'podman'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'weather'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'notion'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-name-regex-substring = 'firefox'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'tor'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'vlc'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-name-regex-substring = 'transmission'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'pycharm'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'datagrip'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'dbeaver'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-name-regex-substring = 'nordpass'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'nordvpn'
run = 'move-node-to-workspace 8'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       20
outer.bottom =     20
outer.top =        45
outer.right =      20

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

[mode.main.binding]
alt-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

cmd-h = []
cmd-alt-h = []

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

cmd-alt-slash = 'layout tiles horizontal vertical'
cmd-alt-comma = 'layout accordion horizontal vertical'

# Modes
alt-shift-semicolon = 'mode service'
alt-shift-enter = 'mode apps'
alt-backslash = 'mode move'
alt-shift-r = 'mode resize'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-o = 'focus-monitor right'
alt-y = 'focus-monitor left'
alt-i = 'focus-monitor up'
alt-u = 'focus-monitor down'

cmd-ctrl-h = 'move left'
cmd-ctrl-j = 'move down'
cmd-ctrl-k = 'move up'
cmd-ctrl-l = 'move right'

cmd-shift-h = 'join-with left'
cmd-shift-j = 'join-with down'
cmd-shift-k = 'join-with up'
cmd-shift-l = 'join-with right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'
cmd-minus = 'workspace 11'
cmd-equal = 'workspace 12'

cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
cmd-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'
cmd-shift-minus = 'move-node-to-workspace 11 --focus-follows-window'
cmd-shift-equal = 'move-node-to-workspace 12 --focus-follows-window'

[mode.resize.binding]
h = 'resize width +50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width -50'
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]
n = ['exec-and-forget open -a /Applications/Notion.app', 'mode main']
c = ['exec-and-forget open -a /Applications/Notion\ Calendar.app', 'mode main']
g = ['exec-and-forget open -a /Applications/Ghostty.app', 'mode main']
f = ['exec-and-forget open -a /Applications/Firefox.app', 'mode main']
m = ['exec-and-forget open -a /System/Applications/Mail.app', 'mode main']

[workspace-to-monitor-force-assignment]
    1 = 'VG34VQL3A'
    2 = 'VG34VQL3A'
    3 = 'VG34VQL3A'
    4 = 'VG34VQL3A'
    5 = 'VG34VQL3A'
    6 = 'VG34VQL3A'
    7 = 'VG34VQL3A'
    8 = 'VG34VQL3A'
    9 = 'VG34VQL3A'
    10 = 'Odyssey G5'
    11 = 'Odyssey G5'
    12 = 'Odyssey G5'

# [workspace-to-monitor-force-assignment]
#     # 1 = 'S6-L'
#     # 2 = 'S6-L'
#     1 = 'VG34VQL3A'
#     2 = 'VG34VQL3A'
#     3 = 'S6-L'
#     4 = 'S6-L'
#     5 = 'S6-L'
#     6 = 'S6-L'
#     7 = 'S6-R'
#     8 = 'S6-R'
#     9 = 'S6-R'
#     10 = 'S6-R'
#     11 = 'S6-R'
#     12 = 'S6-R'
# [workspace-to-monitor-force-assignment]
#     1 = 'main'
#     2 = 'S6-L'
#     3 = 'S6-R'
#     4 = 'main'
#     5 = 'S6-L'
#     6 = 'S6-R'
